script:
  - bin/hugo
deploy:
  provider: s3
  access_key_id: 
    secure: "CKixry7fv3IfWsKaQT7OW2vRgA3YhPMbYvO6xqiXj21q52GIgymSWo7hVQnO7ilnlEErK12KVRQH4kv6FJDJO4mVgXa7B7StJ4kgI0XIuji3n28fZuf+fxBRlEP8dOZAQLm4sVF7Y3E5vO4xLUWDhNRZS3FIgnp2+r9AK3rsl/UAinTgnK8gP1ZAWqEz4ujMt3cR+MrYt7RE/mj+wBUc5jfwSx2WMiCtob99gSQC5tupKCmiVvNEfJCScuhQFpAAtYQo+BuLw33vPk08fjzcscfPGPRgEEOhoeKrPmNgt5eWUvntUXl4B/o+Q7DfWDaIobGUBP9w/VN9+7VpFPEGIF2LJXf0mTjDyjM+gyu3kmwQSZtHQswD3fEqdMgcdUSEp8dSTvrSXv5QcDtGQBCzDoXLkDgZ9S20DlpyqVBUgSN/5vKFI7WAVdrqGMDUBjwMuusoqBSkUvNUV1PhdZygN3xsPbAKoJgHmjjx2EhkNlWRJysTLjJc8x/Pn0zAsAUqa0GJkoUmuIK2m1lBIJyS3lIi3NpNiGMDu3YfMCDvp0K4BN0L3RfaXj5BV83ZfmKqruKdYiPcozrwZtWneVWk109luCBLK6R3F59OAfdWTyk12b0YqJTP+Txa/gDn1jqWpkr5rUEsXcLNYgAgxa8aPINz2QvSrRGawfMbR45kXTE="
  secret_access_key: 
    secure: "PGPoupaqwxY9T24RxleefYE7kA+q2oj96LEZygd0CK3n1g5MJJIqoZJWkPmpu/IKgOx+ppBi1GUKRLbxDMovLNkHaUdlpIAnjlufeOpdNrTwS7wCgbf4euCAj83WKehtI+MU3Vo1ql88bbqXiTQFtUlnbOOPtoGQRcY/2xFy8P96nRftF+DIJFTBKJu+N8ZK32jt6/fiJzRsAnwWeWre+2C60tKp456LoKGmoGkorp/rh3Eg3xTq6IxAaXAfdx6sZ5Sl2fqIchTL4ocPXth8G35JDGyM0M0bpuLi+u781TxNBE67zUKsFgIYVarWk1i8kbKVQ8L4JCtoLNXVXdoUSGSmS4dzkFcg87JSRuL0rf1vINH7ySz3Y0K1RKI6wePSRy+qdvzM7tawXi2jo/SYaQbkbk7F5lwGspIWuub6VpAqxzh+RljpuOs9WwWKMJkcHsCLwZs+n5He7fbGp88pAEh5BznCLU5SCNtjYyvgqyFEWkPyA9Ez72yUMMMuRo3EV6pBGv7nuS5QFXKmk5lnAcEaivhj3OBCdI9t/GzTg/27dQ3WE0MsvPbqfkIOqf/2NbHj2DAyYSrDXgd6GjziOaxTnwFKnl1GBg52pJ05gA+qd/CVpBfozpVPSsLzCWGlWvTWM4pTBC+cbJTV1qV9GQs9osKLOEtyRgBZDFGI/jI="
  bucket: "www.nfsmith.ca"
  skip_cleanup: true
  region: "ca-central-1"
  local_dir: public
branches:
  only:
  - master