baseurl: /website
title: Nathan Smith
subtitle: Physicist, Data Scientist etc..
author: Nathan Smith
simple_search: http://google.com/search
description: Thoughts on programming, physics, life etc.
name: website
markdown: kramdown
markdown_ext: "md"
permalink: /articles/:short_year/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: vim
git:
  branch: master
