markdown: kramdown
highlighter: rouge

repository: https://github.com/nsmith5/website
timezone: America/New_York

defaults:
  -
    scope: 
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
  -
    scope:
      path: "_teaching"
      type: "teaching"
    values:
      layout: "default"

collections:
  posts:
    permalink: /:collection/:year/:month/:day/:title
    output: true
  teaching: 
    permalink: /:collection/:title
    output: true

name: Nathan Smith ;; Physicist, Data Scientist etc..
description: Thoughs on progamming, physics, teaching etc..
baseurl: /website
author: Nathan Smith
simple_search: http://google.com/search

excerpt_separator: <!--more-->  # you can specify your own separator, of course.

exclude: [
  'Gemfile', 
  'Gemfile.lock', 
  'Rakefile',
  'README.md'
]

