markdown: kramdown
highlighter: rouge

repository: https://github.com/nsmith5/website
timezone: America/New_York

defaults:
  -
    scope: 
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
  -
    scope:
      path: "_teaching"
      type: "pages"
    values:
      layout: "default"

collections:
  posts:
    permalink: /:collection/:year/:month/:title
    output: true
  teaching: 
    permalink: /:collection/:title
    output: true

name: Nathan Smith ;; Physicist, Data Scientist etc..
description: Thoughs on progamming, physics, teaching etc..
author: Nathan Smith
url: nathan-smith.ca

simple_search: http://google.com/search

excerpt_separator: <!--more-->  # you can specify your own separator, of course.

exclude: ['vendor', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

